{"uuid": "863f3ffa-fa6a-44a1-9e6f-6839798961e5", "children": ["1aba5361-4e35-43a5-8766-89bd0f7ef19c"], "befores": [{"name": "_xunit_setup_class_fixture_TestAppArticle", "status": "passed", "start": 1673406984242, "stop": 1673406990694}], "afters": [{"name": "_xunit_setup_class_fixture_TestAppArticle::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: A session is either terminated or not started\n\n", "trace": "  File \"C:\\Users\\wyf\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\wyf\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 916, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\wyf\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\python.py\", line 868, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\Users\\wyf\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\python.py\", line 786, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\1Work\\uiAutoTestd\\scripts\\test02_app_article.py\", line 21, in teardown_class\n    GetDriver.quit_app_driver()\n  File \"E:\\1Work\\uiAutoTestd\\tools\\get_driver.py\", line 73, in quit_app_driver\n    cls.__app_driver.quit()\n  File \"C:\\Users\\wyf\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 698, in quit\n    self.execute(Command.QUIT)\n  File \"C:\\Users\\wyf\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\wyf\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 31, in check_response\n    raise wde\n  File \"C:\\Users\\wyf\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"C:\\Users\\wyf\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1673407282624, "stop": 1673407282767}], "start": 1673406984242, "stop": 1673407282767}